<?php
require_once '../config/database.php';
require_once '../config/session_helper.php';
require_once '../classes/Section.php';

// Check if user is logged in and is an admin
if (!isLoggedIn() || !isAdmin()) {
    redirect('public/login.php');
}

if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    $data = [
        'program_id' => (int)$_POST['program_id'],
        'year_level' => $_POST['year_level'],
        'semester' => $_POST['semester'],
        'section_type' => $_POST['section_type'],
        'max_capacity' => (int)$_POST['max_capacity'],
        'academic_year' => sanitizeInput($_POST['academic_year']),
        'status' => 'active'
    ];
    
    // Note: section_name will be auto-generated by addSection() method
    // Format: YY + ProgramCode + Number + TypeCode (e.g., 24BSIS1M)
    
    $section = new Section();
    
    $result = $section->addSection($data);
    
    if (is_array($result) && isset($result['success'])) {
        // New return format with array
        if ($result['success']) {
            $_SESSION['message'] = $result['message'] ?? 'Section added successfully';
        } else {
            $_SESSION['message'] = $result['message'] ?? 'Error adding section. Section may already exist.';
        }
    } else {
        // Legacy return format (boolean) - for backward compatibility
        if ($result) {
            $_SESSION['message'] = 'Section added successfully';
        } else {
            $_SESSION['message'] = 'Error adding section. Section may already exist.';
        }
    }
}

redirect('admin/dashboard.php#sections');
?>


